services:
  knowledge:
    build:
      context: .
      dockerfile: services/knowledge/Dockerfile
    container_name: knowledge
    ports:
      - "50051:50051"
    environment:
      # - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      # - LOG_LEVEL=DEBUG
      - NEO4J_URI=neo4j://neo4j:7687
    env_file:
      - services/knowledge/.env
    depends_on:
      - neo4j
    restart: unless-stopped

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth_file
    volumes:
      - neo4j:/data
    secrets:
      - neo4j_auth_file
    restart: unless-stopped

volumes:
  neo4j:

secrets:
  neo4j_auth_file:
    file: ./secrets/neo4j_auth.txt